packages:
  - "apps"
  - "tools"
  - "tests"
  - "bot/main"
  - "bot/player"
  - "bot/guild"
  - "bot/protect"
  - "bot/logger"
  - "packages/node"
  - "packages/cli"
  - "server/prisma"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
